compilation:
  cloud_properties:
    cpu: 2
    disk: 8192
    ram: 2048
  network: diego1
  reuse_compilation_vms: true
  workers: 6
director_uuid: 802627e1-1d13-4164-a334-c1d06e6d2a69
jobs:
- instances: 1
  name: etcd_z1
  networks:
  - name: diego1
    static_ips:
    - 192.168.100.101
  persistent_disk: 1024
  resource_pool: etcd_z1
  templates:
  - name: etcd
    release: diego
  update:
    max_in_flight: 1
    serial: true

- instances: 1
  name: brain_z1
  networks:
  - name: diego1
  properties:
    metron_agent:
      zone: z1
  resource_pool: brain_z1
  templates:
  - name: consul_agent
    release: cf
  - name: auctioneer
    release: diego
  - name: converger
    release: diego
  - name: runtime_metrics_server
    release: diego
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
    serial: true
- instances: 1
  name: cell_z1
  networks:
  - name: diego1
  properties:
    diego:
      rep:
        zone: z1
    metron_agent:
      zone: z1
  resource_pool: cell_z1
  templates:
  - name: rep
    release: diego
  - name: consul_agent
    release: cf
  - name: garden-linux
    release: diego
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
    serial: false
- instances: 1
  name: cc_bridge_z1
  networks:
  - name: diego1
  properties:
    consul:
      agent:
        services:
        - file_server
        - nsync
        - stager
        - tps
    metron_agent:
      zone: z1
  resource_pool: cc_bridge_z1
  templates:
  - name: stager
    release: diego
  - name: nsync
    release: diego
  - name: tps
    release: diego
  - name: file_server
    release: diego
  - name: consul_agent
    release: cf
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
    serial: false
- instances: 1
  name: route_emitter_z1
  networks:
  - name: diego1
  properties:
    metron_agent:
      zone: z1
  resource_pool: route_emitter_z1
  templates:
  - name: route_emitter
    release: diego
  - name: consul_agent
    release: cf
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
    serial: false
- instances: 1
  name: access_z1
  networks:
  - name: diego1
    static_ips:
    - 192.168.100.102
  properties:
    consul:
      agent:
        services:
        - receptor
        - ssh_proxy
    metron_agent:
      zone: z1
  resource_pool: access_z1
  templates:
  - name: ssh_proxy
    release: diego
  - name: consul_agent
    release: cf
  - name: metron_agent
    release: cf
  - name: receptor
    release: diego
  update:
    max_in_flight: 1
    serial: false
name: cloudfoundry-diego
networks:
- name: diego1
  subnets:
  - cloud_properties:
      name: seperate-network
    dns:
    - 192.168.100.2
    gateway: 192.168.100.2
    range: 192.168.100.0/24
    reserved:
    - 192.168.100.1
    - 192.168.100.3 - 192.168.100.100
    - 192.168.100.140 - 192.168.100.254
    static:
    - 192.168.100.101 - 192.168.100.120
  type: manual
properties:
  consul:
    agent:
      log_level: null
      servers:
        lan:
        - 192.168.100.35
  diego:
    auctioneer:
      etcd:
        machines:
        - 192.168.100.101
      log_level: null
    converger:
      etcd:
        machines:
        - 192.168.100.101
      log_level: debug
    etcd:
      machines:
      - 192.168.100.101
    executor:
      allow_privileged: null
      drain_timeout_in_seconds: 0
      garden:
        address: 127.0.0.1:7777
        network: tcp
      log_level: debug
    file_server:
      cc:
        base_url: https://api.10.65.233.228.xip.io
        basic_auth_password: internal-password
        external_port: 9022
        staging_upload_password: upload-password
        staging_upload_user: upload-user
      log_level: null
    garden-linux:
      allow_networks: null
      disk_quota_enabled: false
      insecure_docker_registry_list: null
      kernel_network_tuning_enabled: false
      listen_address: 0.0.0.0:7777
      listen_network: tcp
    nsync:
      cc:
        base_url: https://api.10.65.233.228.xip.io
        basic_auth_password: internal-password
        external_port: 9022
        staging_upload_password: upload-password
        staging_upload_user: upload-user
      diego_api_url: http://:@receptor.service.consul:8888
      etcd:
        machines:
        - 192.168.100.101
      log_level: debug
    receptor:
      cors_enabled: null
      domain_names:
      - receptor.10.244.0.34.xip.io
      etcd:
        machines:
        - 192.168.100.101
      log_level: debug
      nats:
        machines:
        - 192.168.100.32
        password: nats
        port: 4222
        username: nats
      password: ""
      register_with_router: true
      username: ""
    rep:
      etcd:
        machines:
        - 192.168.100.101
      log_level: debug
    route_emitter:
      diego_api_url: http://:@receptor.service.consul:8888
      log_level: debug
      nats:
        machines:
        - 192.168.100.32
        password: nats
        port: 4222
        username: nats
    runtime_metrics_server:
      diego_api_url: http://:@receptor.service.consul:8888
      etcd:
        machines:
        - 192.168.100.101
      log_level: null
      nats:
        machines:
        - 192.168.100.32
        password: nats
        port: 4222
        username: nats
    ssh_proxy:
      cc:
        external_port: 9022
      diego_api_url: http://:@receptor.service.consul:8888
      enable_cf_auth: true
      enable_diego_auth: true
      host_key: |+
        -----BEGIN RSA PRIVATE KEY-----
        MIIEhgIBAAKB/DMF5qOW+fh608KhX7qBLNHHmfzCfOONd176Oaf8rGht5KdnoNge
        TYSGqBFuYB1r1RbYEVhWAkH/8mW14XRVNmQ4C9eQDFqeWmmaOoSBG5GdP5GUfhI/
        z5vprQw+rnV4gt4InCA7QaR86pLj5sMiUij5OE/CW0dw29+z5E0p5WnQX5+utRmw
        ioQJD8jUDvzFrvzKIdE0HVOEl0agbeXq8U2e9E1de4iR+NiDc1zeiQmDNCIhFJb4
        FL7WqqokL+49SwSWGmOFKAlpj4Dlhx5dDwJWpcDe0XBXCkfcXn8xXNOT+4YBxJUG
        idNMPpLKpDUphZRj8CNBSMkjehIKVwIDAQABAoH8MiCAAQQYvXfeh36HT/IMmGSi
        8mIY1G5tclAfSNzCfS5Jz/XNXcYXnjW09LsdjoocJX9NOx30xeawvCA+SU5WS4uM
        htEscfLVHJ67EubMsPhuNZZPbZpnWuPucPM77ojg+UY4LKpKyVE4G+vvEJKtaTe/
        jQyDJOLKATL4/p5DtbDH7hVZcJVHU94csiE9a9OtyAvSwZLmNxGIBHshFntjcI+/
        hmQSFl3d1iduYGx7oeq3wX0sQ1mk/QksUTHRrlLfSQhLi5ZmH9Hnn/Qw2WeXKVdk
        BvXAUBiHG7Y0qGHXl5FOkB1BSlmk/EOkBk6gWl1a1Kx4A6oyNL4+HsuBAn572PqW
        IDutj4shf8ysI5fLJnvGCygZmk8LPZIlZZqLpDGo+l4iF3VCsd8CU2jKfWqel8+Q
        axdmu/BrQ7xyuWpxoHtKICv+CitI1ivzeYQwRCmjIN84jeGP9Pty4AJzhySegf/h
        n3irIp07wEzdedoj4A3RWWObX+AeubyUqfcCfml3scNb2oBK24RDVGYaUSWkSHBe
        OEU0QlOaJXZ2kCK2rIK/IVI7cD12WpkWTGY782VBmipEXwtMTprQzMrnK25shS+z
        AjCDGXtqr0GjxJh73WRurs1dVk6sqslSp1M/R9fmjGU4vdYL2JfMczEH4+57aOpR
        sW+H0FEYDayKoQJ+Eo8gdjDcYJT7N4jsRfuLesEImVQArV2HbNrMNNh2AWkYnAbw
        5lD3nIgFMFcJhBapTJzZWP4DYrzVOW3MJrEMd3yiHSiXDxm9BMw7h9/05DrCtpRt
        fw8b9zOyHrPdCiz9WteGXexE6/hi8ZpOqn3hJ7EiwPWRTK5gappQ3UJfAn4Tr0t2
        cwZtO4uNPCPcirzqkacTkgJeqEpY4ERtv+NXF1FLdfD6MC3ayuRN/mN0EWx0UbI8
        gVZb/XoOWzpeBJeOnKKfLIIUG+P9rQPY9IAVFclUnXPy0KDzPjcCLHMejokSOu2p
        VtXXxY4/huFZHWflcxM56NV9Q5QWDq8+rQECfjQTbNbd4ehbC/Q5EZ1SIzeaSLrn
        0ICmiRajnISbje5vPntqPXjBkbiVGx31qOaZ+DlGGLOyzW/GP5X4NOUwza2bYh3q
        nnzwBhoGLZfvoes5Nw06leOdVqcvIjLIDhb+XbiiEeAnONUp+BAKzDYOIp7K+LPe
        1rHeshh0P/QfCQ==
        -----END RSA PRIVATE KEY-----
      servers:
      - 192.168.100.102
    ssl:
      skip_cert_verify: true
    stager:
      cc:
        base_url: https://api.10.65.233.228.xip.io
        basic_auth_password: internal-password
        external_port: 9022
        staging_upload_password: upload-password
        staging_upload_user: upload-user
      diego_api_url: http://:@receptor.service.consul:8888
      insecure_docker_registry: false
      log_level: null
    tps:
      cc:
        base_url: https://api.10.65.233.228.xip.io
        basic_auth_password: internal-password
        external_port: 9022
        staging_upload_password: upload-password
        staging_upload_user: upload-user
      diego_api_url: http://:@receptor.service.consul:8888
      log_level: null
      traffic_controller_url: wss://doppler.10.65.233.228.xip.io:443
  etcd:
    machines:
    - 192.168.100.45
    - 192.168.100.46
  loggregator_endpoint:
    shared_secret: secret
  metron_agent:
    deployment: cloudfoundry-diego
  nats:
    machines:
    - 192.168.100.32
    password: nats
    port: 4222
    user: nats
  syslog_daemon_config:
    address: null
    port: null
releases:
- name: diego
  version: latest
- name: cf
  version: latest
resource_pools:
- cloud_properties:
    cpu: 1
    disk: 10240
    ram: 2048
  name: access_z1
  network: diego1
  stemcell:
    name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    cpu: 1
    disk: 10240
    ram: 2048
  name: brain_z1
  network: diego1
  stemcell:
    name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    cpu: 1
    disk: 10240
    ram: 2048
  name: cc_bridge_z1
  network: diego1
  stemcell:
    name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    cpu: 2
    disk: 40960
    ram: 8192
  name: cell_z1
  network: diego1
  stemcell:
    name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    cpu: 1
    disk: 40960
    ram: 2048
  name: etcd_z1
  network: diego1
  stemcell:
    name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    cpu: 1
    disk: 10240
    ram: 2048
  name: route_emitter_z1
  network: diego1
  stemcell:
    name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-120000
