iaas_settings:
  stemcell:
    name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
    version: latest
  subnet_configs:
    - name: diego1
      subnets:
      - cloud_properties:
          name: seperate-network
        dns:
        - 192.168.100.2
        gateway: 192.168.100.2
        range: 192.168.100.0/24
        reserved:
        - 192.168.100.1
        - 192.168.100.3 - 192.168.100.100
        - 192.168.100.140 - 192.168.100.254
        static:
        - 192.168.100.101 - 192.168.100.120
      type: manual
    - name: diego2
      type: manual
      subnets:
      - cloud_properties: {}
        range: 10.244.18.0/30
        reserved:
        - 10.244.18.1
        static:
        - 10.244.18.2
      - cloud_properties: {}
        range: 10.244.18.4/30
        reserved:
        - 10.244.18.5
        static: []
      - cloud_properties: {}
        range: 10.244.18.8/30
        reserved:
        - 10.244.18.9
        static: []
      - cloud_properties: {}
        range: 10.244.18.12/30
        reserved:
        - 10.244.18.13
        static: []
      - cloud_properties: {}
        range: 10.244.18.16/30
        reserved:
        - 10.244.18.17
        static: []
      - cloud_properties: {}
        range: 10.244.18.20/30
        reserved:
        - 10.244.18.21
        static: []
      - cloud_properties: {}
        range: 10.244.18.24/30
        reserved:
        - 10.244.18.25
        static: []
      - cloud_properties: {}
        range: 10.244.18.28/30
        reserved:
        - 10.244.18.29
        static: []
      - cloud_properties: {}
        range: 10.244.18.32/30
        reserved:
        - 10.244.18.33
        static: []
      - cloud_properties: {}
        range: 10.244.18.36/30
        reserved:
        - 10.244.18.37
        static: []
      - cloud_properties: {}
        range: 10.244.18.40/30
        reserved:
        - 10.244.18.41
        static: []
      - cloud_properties: {}
        range: 10.244.18.44/30
        reserved:
        - 10.244.18.45
        static:
        - 10.244.18.46
      - cloud_properties: {}
        range: 10.244.18.48/30
        reserved:
        - 10.244.18.49
        static:
        - 10.244.18.50
      - cloud_properties: {}
        range: 10.244.18.52/30
        reserved:
        - 10.244.18.53
        static:
        - 10.244.18.54
      - cloud_properties: {}
        range: 10.244.18.56/30
        reserved:
        - 10.244.18.57
        static:
        - 10.244.18.58
      - cloud_properties: {}
        range: 10.244.18.60/30
        reserved:
        - 10.244.18.61
        static:
        - 10.244.18.62
      - cloud_properties: {}
        range: 10.244.18.64/30
        reserved:
        - 10.244.18.65
        static:
        - 10.244.18.66
      - cloud_properties: {}
        range: 10.244.18.68/30
        reserved:
        - 10.244.18.69
        static:
        - 10.244.18.70
      - cloud_properties: {}
        range: 10.244.18.72/30
        reserved:
        - 10.244.18.73
        static:
        - 10.244.18.74
      - cloud_properties: {}
        range: 10.244.18.76/30
        reserved:
        - 10.244.18.77
        static:
        - 10.244.18.78
      - cloud_properties: {}
        range: 10.244.18.80/30
        reserved:
        - 10.244.18.81
        static:
        - 10.244.18.82
    - name: diego3
      type: manual
      subnets:
      - cloud_properties: {}
        range: 10.244.20.0/30
        reserved:
        - 10.244.20.1
        static:
        - 10.244.20.2
      - cloud_properties: {}
        range: 10.244.20.4/30
        reserved:
        - 10.244.20.5
        static: []
      - cloud_properties: {}
        range: 10.244.20.8/30
        reserved:
        - 10.244.20.9
        static: []
      - cloud_properties: {}
        range: 10.244.20.12/30
        reserved:
        - 10.244.20.13
        static: []
      - cloud_properties: {}
        range: 10.244.20.16/30
        reserved:
        - 10.244.20.17
        static: []
      - cloud_properties: {}
        range: 10.244.20.20/30
        reserved:
        - 10.244.20.21
        static: []
      - cloud_properties: {}
        range: 10.244.20.24/30
        reserved:
        - 10.244.20.25
        static: []
      - cloud_properties: {}
        range: 10.244.20.28/30
        reserved:
        - 10.244.20.29
        static: []
      - cloud_properties: {}
        range: 10.244.20.32/30
        reserved:
        - 10.244.20.33
        static: []
      - cloud_properties: {}
        range: 10.244.20.36/30
        reserved:
        - 10.244.20.37
        static: []
      - cloud_properties: {}
        range: 10.244.20.40/30
        reserved:
        - 10.244.20.41
        static: []
      - cloud_properties: {}
        range: 10.244.20.44/30
        reserved:
        - 10.244.20.45
        static:
        - 10.244.20.46
      - cloud_properties: {}
        range: 10.244.20.48/30
        reserved:
        - 10.244.20.49
        static:
        - 10.244.20.50
      - cloud_properties: {}
        range: 10.244.20.52/30
        reserved:
        - 10.244.20.53
        static:
        - 10.244.20.54
      - cloud_properties: {}
        range: 10.244.20.56/30
        reserved:
        - 10.244.20.57
        static:
        - 10.244.20.58
      - cloud_properties: {}
        range: 10.244.20.60/30
        reserved:
        - 10.244.20.61
        static:
        - 10.244.20.62
      - cloud_properties: {}
        range: 10.244.20.64/30
        reserved:
        - 10.244.20.65
        static:
        - 10.244.20.66
      - cloud_properties: {}
        range: 10.244.20.68/30
        reserved:
        - 10.244.20.69
        static:
        - 10.244.20.70
      - cloud_properties: {}
        range: 10.244.20.72/30
        reserved:
        - 10.244.20.73
        static:
        - 10.244.20.74
      - cloud_properties: {}
        range: 10.244.20.76/30
        reserved:
        - 10.244.20.77
        static:
        - 10.244.20.78
      - cloud_properties: {}
        range: 10.244.20.80/30
        reserved:
        - 10.244.20.81
        static:
        - 10.244.20.82
  compilation_cloud_properties:
    cpu: 2
    disk: 8192
    ram: 2048
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties:
        cpu: 1
        disk: 10240
        ram: 2048
    - name: access_z2
      cloud_properties: {}
    - name: access_z3
      cloud_properties: {}
    - name: brain_z1
      cloud_properties:
        cpu: 1
        disk: 10240
        ram: 2048
    - name: brain_z2
      cloud_properties: {}
    - name: brain_z3
      cloud_properties: {}
    - name: cc_bridge_z1
      cloud_properties:
        cpu: 1
        disk: 10240
        ram: 2048
    - name: cc_bridge_z2
      cloud_properties: {}
    - name: cc_bridge_z3
      cloud_properties: {}
    - name: cell_z1
      cloud_properties:
        cpu: 2
        disk: 40960
        ram: 8192
    - name: cell_z2
      cloud_properties: {}
    - name: cell_z3
      cloud_properties: {}
    - name: database_z1
      cloud_properties:
        cpu: 1
        disk: 40960
        ram: 2048
    - name: database_z2
      cloud_properties: {}
    - name: database_z3
      cloud_properties: {}
    - name: route_emitter_z1
      cloud_properties:
        cpu: 1
        disk: 10240
        ram: 2048
    - name: route_emitter_z2
      cloud_properties: {}
    - name: route_emitter_z3
      cloud_properties: {}
