---

meta:
  stemcell:
    name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
    version: latest

releases:
- name: logsearch
  version: 23.0.0
- name: logsearch-for-cloudfoundry
  version: 7+dev.1

name: logsearch
director_uuid: cbd4b944-f941-46bb-80d1-51714f3c07fe

jobs:
- name: elasticsearch_data
  instances: 1
- name: ingestor_firehose
  instances: 1
  networks:
  - name: default
  resource_pool: medium
  templates:
  - name: ingestor_cloudfoundry-firehose
    release: logsearch-for-cloudfoundry

networks:
- name: default
  subnets:
    - range: 192.168.200.0/24
      gateway: 192.168.200.1
      dns: [192.168.200.1]
      reserved:
        - 192.168.200.2 - 192.168.200.90
        - 192.168.200.130 - 192.168.200.254
      static:
        - 192.168.200.91 - 192.168.200.110
      cloud_properties: {name: cf-network}

properties:
  push-kibana:
    app_memory: 1024m
    oauth2_client_secret: secret
  cloudfoundry:
    skip_ssl_validation: true
    system_domain: 10.65.192.249.xip.io
    firehose_port: 443
    firehose_user: admin
    firehose_password: admin
    admin_username: admin
    admin_password: admin
    admin_client_secret: "secret"
    api_access_security_group: public_networks
  nats:
    machines:
    - 192.168.200.3
    password: nats
    port: 4222
    user: nats
