---
name: concourse

# replace with bosh status --uuid
director_uuid: cbd4b944-f941-46bb-80d1-51714f3c07fe

# pick a sane db name and password
atc_db_name: &atc-db-name atc
atc_db_role: &atc-db-role
  name: atc
  password: atc

discovery_ip: &discovery_static_ip 192.168.200.131

# replace all addresses with your network's IP range
#
# e.g. X.X.0.2 -> 10.0.0.2
networks:
  - name: concourse
    type: manual
    subnets:
      - range: 192.168.200.0/24
        gateway: 192.168.200.1
        dns: [192.168.200.1]
        reserved:
          - 192.168.200.2 - 192.168.200.130
          - 192.168.200.160 - 192.168.200.254
        static:
          - 192.168.200.131 - 192.168.200.140
        cloud_properties: {name: cf-network}

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
    networks:
      - name: concourse
        static_ips: [*discovery_static_ip]
    properties:
      consul:
        agent:
          mode: server

  - name: web
    instances: 1
    resource_pool: web
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: tsa}
      - {release: concourse, name: atc}
    networks: [{name: concourse}]
    properties:
      atc:
        publicly_viewable: true
        basic_auth_username: atc
        basic_auth_password: atc
        postgresql:
          database: *atc-db-name
          role: *atc-db-role
        external_url: http://10.65.192.249:8080

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: db
    instances: 1
    resource_pool: databases
    persistent_disk_pool: database
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: postgresql}
    networks: [{name: concourse}]
    properties:
      postgresql:
        databases: [{name: *atc-db-name}]
        roles: [*atc-db-role]

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: worker
    instances: 1
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

disk_pools:
  - name: database
    disk_size: 10240
    cloud_properties:
      type: gp2

resource_pools:
  - name: web
    network: concourse
    stemcell: &stemcell
      name: bosh-vcloud-esxi-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      cpu: 1
      ram: 2_048
      disk: 4_096

  - name: discovery
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      cpu: 1
      ram: 2_048
      disk: 4_096

  - name: databases
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      cpu: 1
      ram: 2_048
      disk: 4_096

  - name: workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      cpu: 2
      ram: 2_048
      disk: 32_768

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    cpu: 2
    ram: 3_840
    disk: 32_768

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
